package enigma

var HistoricRotors = Rotors{
	*NewRotor("EKMFLGDQVZNTOWYHXUSPAIBRCJ", "I", "Q"),
	*NewRotor("AJDKSIRUXBLHWTMCQGZNPYFVOE", "II", "E"),
	*NewRotor("BDFHJLCPRTXVZNYEIWGAKMUSQO", "III", "V"),
	*NewRotor("ESOVPZJAYQUIRHXLNFTGKDCMWB", "IV", "J"),
	*NewRotor("VZBRGITYUPSDNHLXAWMJQOFECK", "V", "Z"),
	*NewRotor("JPGVOUMFYQBENHZRDKASXLICTW", "VI", "ZM"),
	*NewRotor("NZJHGRCXMYSWBOUFAIVLPEKQDT", "VII", "ZM"),
	*NewRotor("FKQHTLXOCBJSPDZRAMEWNIUYGV", "VIII", "ZM"),
	*NewRotor("LEYJVCNIXWPBQMDRTAKZGFUHOS", "Beta", ""),
	*NewRotor("FSOKANUERHMBTIYCWLQPZXVGJD", "Gamma", ""),
}

var HistoricReflectors = Reflectors{
	*NewReflector("EJMZALYXVBWFCRQUONTSPIKHGD", "A"),
	*NewReflector("YRUHQSLDPXNGOKMIEBFZCWVJAT", "B"),
	*NewReflector("FVPJIAOYEDRZXWGCTKUQSBNMHL", "C"),
	*NewReflector("ENKQAUYWJICOPBLMDXZVFTHRGS", "B-thin"),
	*NewReflector("RDOBJNTKVEHMLFCWZAXGYIPSUQ", "C-thin"),
}
